Adicionando os parâmetros para a utilização do pattern recomendado na ITU_R S.1528
Radio-Spectrum/SHARC pull request #106
Opened 2024-11-01 13:02 UTC by joaocabeca2

Adicionando os parâmetros para a utilização do pattern recomendado na ITU_R S.1528 e consertando alguns blocos de códigos que davam erro ao realizar o debbug

2024-11-06 12:58 UTC, brunohcfaria requested changes

2024-11-06 12:58 UTC, brunohcfaria commented on sharc/antenna/antenna_s1528.py
> +sys.path.append(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".."))
Não é necessário adicionar esse arquivo (nem os outros ao path). Tente configurar seu ambiente para que os arquivos do simulador estejam no path do venv.

2024-11-06 12:58 UTC, brunohcfaria commented on sharc/antenna/antenna_fss_ss.py
> +sys.path.append(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".."))
Não é necessário adicionar esse arquivo (nem os outros ao path). Tente configurar seu ambiente para que os arquivos do simulador estejam no path do venv.

2024-11-06 12:58 UTC, brunohcfaria commented on sharc/parameters/parameters_fss_ss.py
> +    # Parameters if antenna_pattern = ITU_R S.1528
Usar zero como padrão nesses parâmetros é inválido. Não podemos ter parâmetros padrão diferentes? Vindo da especificação?

2024-11-06 12:58 UTC, brunohcfaria commented on sharc/parameters/parameters_fss_ss.py
> +    # Parameters if antenna_pattern = ITU_R S.1528
Se sim, revise todos os arquivos de parâmetros.

2024-11-06 17:25 UTC, joaocabeca2 commented
Conflitos resolvidos, retirando alteração do bloco de código no arquivo parameters_base.py, onde havia um erro que passava pelo try/execept na hora da conversão dos parâmetros. esse erro já havia sido consertando em um commit anterior.

2024-11-07 14:14 UTC, brunohcfaria approved these changes

2024-11-07 14:16 UTC, merged